### ISSUE TITLE
Subscription tag raise Error "Could not interpret the value as a list" in cloud pub/sub

### ISSUE THREAD

**Issue by stat-kwon** [cloudforet-io/plugin-google-cloud-inven-collector#29]
```
Traceback (most recent call last):
  File "/Users/seolmin/project/plugin-google-cloud-inven-collector/src/spaceone/inventory/manager/pub_sub/subscription_manager.py", line 109, in collect_cloud_service
    subscription_resource = SubscriptionResource({
  File "/Users/seolmin/project/plugin-google-cloud-inven-collector/venv/lib/python3.8/site-packages/schematics/models.py", line 232, in __init__
    data = self._convert(raw_data,
  File "/Users/seolmin/project/plugin-google-cloud-inven-collector/venv/lib/python3.8/site-packages/schematics/models.py", line 299, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "/Users/seolmin/project/plugin-google-cloud-inven-collector/venv/lib/python3.8/site-packages/schematics/transforms.py", line 428, in convert
    return import_loop(cls, mutable, raw_data, import_converter, **kwargs)
  File "/Users/seolmin/project/plugin-google-cloud-inven-collector/venv/lib/python3.8/site-packages/schematics/transforms.py", line 174, in import_loop
    raise DataError(errors, data)
```

**Comment by stat-kwon** [comment]
In the meantime, collection errors that occurred due to tags processing have been resolved.

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/83386688/204084660-2527e7a9-23e6-4c49-bde8-6317f0f54d1e.png">
