### ISSUE TITLE
implement Cloud Pub/Sub service

### ISSUE THREAD

**Issue by stat-kwon** [cloudforet-io/plugin-google-cloud-inven-collector#8]
## Classification
<img width="281" alt="image" src="https://user-images.githubusercontent.com/83386688/197330556-45a534ee-c57e-412a-a820-3d7e8cf1a1cf.png">

According to the picture above, you can see that there are a total of 4 Cloud Service Types.  
Thus, the classification of services can be confirmed.

<br>

**Pub/Sub(SQS)**
* Cloud Service Group : Pub/Sub
* Cloud Service Type : Topic, Subscription, Snapshot, Schema
* Labels : Application Integration
* Service Code : Cloud Pub/Sub

For ease of understanding, the service name specified in (service) is the service name provided by Amazone.

**Comment by stat-kwon** [comment]
After testing the Pub/Sub service in dev, some problems were found.

1. A phenomenon in which both topics and subscriptions that actually exist are not displayed.
	ex ) In fact, 8 subscriptions should appear, but only 1 is output.
	
![스크린샷 2022-10-24 오후 1 06 43](https://user-images.githubusercontent.com/83386688/197446813-f7a1ea1c-f2ee-4b1e-bb97-8eb9187ed36a.png)

2. When the type to be specified in the table is incorrect
ex ) After 8 examples are printed normally, a full investigation is required for fields that are not normal.
![image](https://user-images.githubusercontent.com/83386688/197447070-d5466b29-404d-4271-89fa-7957e3937bf7.png)

3. When searching, Int is treated as String, so comparison is impossible
ex ) It should also enable searches such as `Ack deadline > 10`
![image](https://user-images.githubusercontent.com/83386688/197447364-ef9dc36a-0d26-4d12-9ab0-055b453b0b3f.png)


Accordingly, the work should proceed to the next step
- [ ] Topic, Subscription, Snapshot and Scheam are all displayed normally.
- [ ] Check that all planned fields are exposed normally
- [ ] Changed to work normally for Int field of Search function

**Comment by stat-kwon** [comment]
Currently, snapshot is returning the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spaceone_inventory-1.10.3rc1-py3.8.egg/spaceone/inventory/api/v1/cloud_service.py", line 45, in list
    cloud_svc_vos, total_count = cloud_svc_service.list(params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 58, in wrapped_func
    return _pipeline(func, self, params, append_meta)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 121, in _pipeline
    raise e
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 107, in _pipeline
    response_or_iterator = func(self, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 41, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 64, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 180, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone_inventory-1.10.3rc1-py3.8.egg/spaceone/inventory/service/cloud_service_service.py", line 322, in list
    return self.cloud_svc_mgr.list_cloud_services(query)
  File "/usr/local/lib/python3.8/site-packages/spaceone_inventory-1.10.3rc1-py3.8.egg/spaceone/inventory/manager/cloud_service_manager.py", line 77, in list_cloud_services
    return self.cloud_svc_model.query(**query, target=target)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/model/mongo_model/__init__.py", line 575, in query
    raise ERROR_DB_QUERY(reason=e)
spaceone.core.error.ERROR_DB_QUERY:
	error_code = ERROR_DB_QUERY
	status_code = INTERNAL
	message = Database query failed. (reason = Cannot resolve field "project")
```

**Comment by stat-kwon** [comment]
![image](https://user-images.githubusercontent.com/83386688/197522731-e317ce7c-ba4e-4f73-83e2-c69f5f694547.png)

All bugs occurring in the dev environment have been fixed, and there is no problem between console operation.

**Comment by stat-kwon** [comment]
After the Pub/Sub service is reflected in the README.md, the issue will be closed.

**Comment by stat-kwon** [comment]
According to @jihyungSong' feedback
If the definition code is long, it may be limited to provide in the console, so it is suggested to change it to access the popup after processing the show option.

**AS-IS**
<img width="1247" alt="스크린샷 2022-10-26 오전 12 15 03" src="https://user-images.githubusercontent.com/83386688/197815416-9efe1d3c-af4f-4546-8844-3de6239d9372.png">

**TO-BE**
<img width="858" alt="image" src="https://user-images.githubusercontent.com/83386688/197815672-d578d91c-1fb0-436f-9c0e-c153389be555.png">
